apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  annotations:
    description: Defines how to build the application
    template.alpha.openshift.io/wait-for-ready: 'true'
  labels:
    app: openshift-tasks
    template: openshift-tasks
  name: openshift-tasks
spec:
  output:
    to:
      kind: ImageStreamTag
      name: 'openshift-tasks:latest'
  runPolicy: Serial
  source:
    git:
      uri: 'https://github.com/wkulhanek/openshift-tasks.git'
    type: Git
  strategy:
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: 'eap70-basic-s2i'
        namespace: openshift
    type: Source
  triggers:
    - imageChange:
      type: ImageChange
    - type: ConfigChange`
